name: pr-review-workflow
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths-ignore: #the workflow will not run if only these files are changed
      - README.md
      - docs/**

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: validate pr title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          PATTERN='^(feat|fix|chore|docs|refactor|test|perf|ci|build|revert): .+'

          echo "Checking PR title: $PR_TITLE"

          if [[ ! "$PR_TITLE" =~ $PATTERN ]]; then
            echo "::error::PR title must follow semantic format"
            exit 1
          fi

          echo "✅ PR title is valid"

  lint:
    runs-on: ubuntu-latest
    needs: [validate-pr-title]
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Install nodeJS
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  type-check:
    runs-on: ubuntu-latest
    needs: [validate-pr-title]
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Install nodeJS
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run type-check

  unit-test-with-coverage:
    runs-on: ubuntu-latest
    needs: [lint, type-check]
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Install nodeJS
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm  run test -- --coverage

  build-android:
    runs-on: ubuntu-latest
    needs: [unit-test-with-coverage]
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Install nodeJS
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci

      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}

      - name: Build Android Debug
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload android build to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

  build-ios:
    runs-on: macos-latest
    needs: [unit-test-with-coverage]
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Install nodeJS
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci

      # - name: Cache CocoaPods
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ios/Pods
      #       ~/.cocoapods
      #       ~/Library/Caches/CocoaPods
      #     key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pods-

      # - name: Install cocoaPods
      #   run: |
      #     cd ios
      #     pod install --deployment

      - name: Build iOS Debug
        run: |
          cd ios
          xcodebuild -workspace DemoApp.xcworkspace -scheme DemoApp -configuration Debug -sdk iphonesimulator -derivedDataPath build

      - name: Upload ios build to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug-app
          path: ios/build/Build/Products/Debug-iphonesimulator/DemoApp.app
  notify-pr-owner:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    if: success() && github.event_name == 'pull_request'

    steps:
      - name: Notify pr owner
        uses: actions/github-script@v8
        with:
          script: |
            const pr = context.payload.pull_request;

            const MARKER = '<!-- CI-QUALITY-GATE -->';

            const jobs = [
              { name: 'validate-pr-title', status: '✅ Passed' },
              { name: 'lint', status: '✅ Passed' },
              { name: 'type-check', status: '✅ Passed' },
              { name: 'unit-test-with-coverage', status: '✅ Passed' },
              { name: 'build-android', status: '✅ Passed' },
              { name: 'build-ios', status: '✅ Passed' },
            ];

            let summary = `${MARKER}
            ## ✅ Quality Gate passed

            Hello @${pr.user.login}, all checks have passed!

            | Job | Status |
            | --- | --- |
            `;

            for (const job of jobs) {
              summary += `| ${job.name} | ${job.status} |\n`;
            }

            summary += `\nReady to merge 🚀`;

             // 1️⃣ Get existing comments
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
            });

            // 2️⃣ Find existing CI comment
            const existingComment = comments.find(comment =>
              comment.body.includes(MARKER)
            );

            if (existingComment) {
              // 3️⃣ Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: summary,
              });
            } else {
              // 4️⃣ Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: summary,
              });
            }
